image: node:14.3.0-alpine3.11

stages:
  - install
  - tests
  - build
  - release

install:
  tags:
    - golang
    - linux
  stage: install
  allow_failure: false
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/

tests:
  tags:
    - golang
    - linux
  stage: tests
  when: on_success
  script:
    - npm run lint
    - npm run test

build:
  tags:
    - golang
    - linux
  stage: build
  when: on_success
  script:
    - npm run build
  artifacts:
    paths:
      - lib/

release_beta:
  stage: release
  tags:
    - golang
    - linux
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+-beta\.\d+$/'
      when: on_success
  script:
    - npm version $CI_COMMIT_TAG
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm publish --tag beta

release_stable:
  stage: release
  tags:
    - golang
    - linux
  rules:
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
      when: on_success
  script:
    - npm version $CI_COMMIT_TAG
    - echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > ~/.npmrc
    - npm publish